import React from 'react'

import {FormFields, Loader} from '../components'

const Home = () => {

  return (
    <div className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[30px]'>The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-full">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI.</p>
      </div>

      <div className="mt-16">
        <FormFields />
      </div>

      <div className="mt-10">
        <Loader />
      </div>

    </div>
  )
}

export default Home